cloudinary-core/src/main/java/com/cloudinary/Util.java
support eager transformations as string
=> eager upload params can be both string or List<Transformation>

cloudinary-http44/src/main/java/com/cloudinary/http44/UploaderStrategy.java
There was a typo at an exception message in UploaderStrategy class.
=> Fixing typo on exception

cloudinary-android/src/main/java/com/cloudinary/android/MultipartUtility.java
Fixed OOM crash while uploading files on devices with limited memory
=> Fix for #55

cloudinary-core/src/main/java/com/cloudinary/ArchiveParams.java
Added support for `skip_transformation_name` parameter when generating archives
=> Add `skip_transformation_name` parameter to generate archive.

cloudinary-core/src/main/java/com/cloudinary/ArchiveParams.java
Added support for `expires_at` parameter for generate archive
=> Add expires at to generate archive

cloudinary-android/src/main/java/com/cloudinary/android/UploaderStrategy.java
- Eliminate logs like:
A resource was acquired at attached stack trace but never released.
See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'end' not called
at dalvik.system.CloseGuard.open(CloseGuard.java:180)
at java.util.zip.Inflater.<init>(Inflater.java:82)
at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:827)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
at …
=> Close streams in UploaderStrategy

cloudinary-core/src/main/java/com/cloudinary/transformation/FetchLayer.java, cloudinary-core/src/test/java/com/cloudinary/test/CloudinaryTest.java
Added support for `fetch` as overlay and underlay layer.
=> Add support for fetch overlay/underlay

gradle.properties
See https://github.com/gradle/gradle/issues/11308
=> Fix issue with maven central and gradle signatures.

cloudinary-core/src/test/java/com/cloudinary/analytics/AnalyticsTest.java
Fix for analytics test that was based on SDK version.
Modified the test to use hard-coded version instead.
=> Fix analytics test

.github/pull_request_template.md
Add a template for future pull requests.
=> Add template for PR

cloudinary-core/src/main/java/com/cloudinary/Uploader.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractUploaderTest.java
Add a function to get tags as an array.
=> Add tags as an array

cloudinary-core/src/main/java/com/cloudinary/Api.java, cloudinary-core/src/main/java/com/cloudinary/EagerTransformation.java, cloudinary-core/src/main/java/com/cloudinary/Transformation.java, cloudinary-core/src/test/java/com/cloudinary/TransformationTest.java
Fix create, update and delete to receive transformations as parameter
=> Fix transformations API call

samples/photo_album/pom.xml, samples/photo_album_gae/pom.xml
=> Update Spring framework version to account for cve-2022-22965

build.gradle, cloudinary-core/build.gradle, cloudinary-http42/build.gradle, cloudinary-http43/build.gradle, cloudinary-http44/build.gradle, cloudinary-http45/build.gradle, cloudinary-taglib/build.gradle, cloudinary-test-common/build.gradle
Fix the publishing to `SonaType` process
Update the publishing script to use this [repo](https://github.com/gradle-nexus/publish-plugin)
- [] Adds more tests
=> Fix publishing to nexus script

samples/photo_album/pom.xml, samples/photo_album_gae/pom.xml
Bump spring core version
Bump `springframework.data` version
=> Bump spring frameworks version

cloudinary-core/src/main/java/com/cloudinary/Util.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java
Add the following parameters to the update resource API call
1. asset_folder
2. unique_display_name
Add relevant test as well
=> Add asset_folder, unique_display_name  to update resource API call

cloudinary-core/src/main/java/com/cloudinary/Api.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java, cloudinary-test-common/src/main/java/com/cloudinary/test/MockableTest.java, cloudinary-test-common/src/main/java/com/cloudinary/test/helpers/Feature.java
Add new API call , get resources by asset folder
=> Get resources by asset folder

cloudinary-core/src/main/java/com/cloudinary/Util.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractStructuredMetadataTest.java
Add tests for `clear_invalid` parameter for: 
1. Update resource Admin API
2. Update meta data Upload API
=> Add test for `clear_invalid` parameter

cloudinary-core/src/main/java/com/cloudinary/Api.java, cloudinary-core/src/main/java/com/cloudinary/Util.java, cloudinary-taglib/src/main/java/com/cloudinary/taglib/CloudinaryUploadTag.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractUploaderTest.java
Add support to `media_metadata` base on `image_metadata` parameter
- [] Adds more tests
=> Add support for `media_metadata` parameter

samples/photo_album/pom.xml
Update Update SQL version on sample project
=> Update Hyper SQL version

cloudinary-core/src/main/java/com/cloudinary/Cloudinary.java, cloudinary-core/src/main/java/com/cloudinary/Search.java, cloudinary-core/src/main/java/com/cloudinary/SearchFolders.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractSearchTest.java
Add Search folders functionality.
=> Add Search folders functionality

cloudinary-core/src/main/java/com/cloudinary/Search.java, cloudinary-core/src/main/java/com/cloudinary/Url.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractSearchTest.java
=> Add `toUrl() to Search API

cloudinary-core/src/main/java/com/cloudinary/Api.java, cloudinary-core/src/main/java/com/cloudinary/Util.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractUploaderTest.java, cloudinary-test-common/src/main/java/com/cloudinary/test/MockableTest.java
=> Add visual search support

cloudinary-core/src/test/java/com/cloudinary/test/CloudinaryTest.java
Add unit test to verify working with fetch video overlay.
=> Add unit test for fetch video overlay

cloudinary-core/src/main/java/com/cloudinary/utils/Analytics.java, cloudinary-core/src/test/java/com/cloudinary/analytics/AnalyticsTest.java
Upload analytics token to algo C
=> Update analytics token

cloudinary-core/src/main/java/com/cloudinary/Configuration.java, cloudinary-core/src/main/java/com/cloudinary/Url.java, cloudinary-core/src/test/java/com/cloudinary/test/CloudinaryTest.java
Add support to use fetch format
=> Add support to use fetch format

cloudinary-core/src/main/java/com/cloudinary/Uploader.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractUploaderTest.java
Add notification_url support to rename and destroy
=> Add notification_url support to rename and destroy

cloudinary-core/src/main/java/com/cloudinary/utils/Analytics.java, cloudinary-core/src/test/java/com/cloudinary/analytics/AnalyticsTest.java
Add analytics feature flag support
=> Add analytics feature flag support

cloudinary-core/src/main/java/com/cloudinary/metadata/MetadataField.java, cloudinary-core/src/main/java/com/cloudinary/metadata/Restrictions.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractStructuredMetadataTest.java, cloudinary-test-common/src/main/java/com/cloudinary/test/MetadataTestHelper.java
Add restrictions field to metadata
=> Add restrictions field to metadata

cloudinary-core/src/main/java/com/cloudinary/provisioning/Account.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractAccountApiTest.java
Add ability to get/add/update access keys
=> Manage access keys

cloudinary-core/src/main/java/com/cloudinary/Api.java, cloudinary-core/src/main/java/com/cloudinary/Search.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractSearchTest.java
Add selective response support
=> Add selective response support

cloudinary-core/src/main/java/com/cloudinary/Api.java, cloudinary-core/src/main/java/com/cloudinary/strategies/AbstractApiStrategy.java, cloudinary-http42/src/main/java/com/cloudinary/http42/ApiStrategy.java, cloudinary-http43/src/main/java/com/cloudinary/http43/ApiStrategy.java, cloudinary-http44/src/main/java/com/cloudinary/http44/ApiStrategy.java, cloudinary-http45/src/main/java/com/cloudinary/http45/ApiStrategy.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java
=> Add analyze api

cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractUploaderTest.java
Add `filename` to upload large test to make sure it returns as part of the response.
=> Add filename test to upload large

cloudinary-core/src/main/java/com/cloudinary/Api.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java
=> Add rename folder api

cloudinary-core/src/main/java/com/cloudinary/Api.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java, cloudinary-test-common/src/main/java/com/cloudinary/test/helpers/Feature.java
Add delete backup asset version api
=> Add delete backup asset version api

cloudinary-core/src/main/java/com/cloudinary/Api.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java
=> Add config api call

cloudinary-core/src/main/java/com/cloudinary/Api.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java
=> Fix rename folder endpoint

cloudinary-core/src/main/java/com/cloudinary/Api.java, cloudinary-core/src/main/java/com/cloudinary/metadata/MetadataRule.java, cloudinary-core/src/main/java/com/cloudinary/metadata/MetadataRuleCondition.java, cloudinary-core/src/main/java/com/cloudinary/metadata/MetadataRuleResult.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractStructuredMetadataTest.java, cloudinary-test-common/src/main/java/com/cloudinary/test/helpers/Feature.java
Add conditional metadata rules
=> Add conditional metadata rules

cloudinary-core/src/main/java/com/cloudinary/metadata/MetadataField.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractStructuredMetadataTest.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractUploaderTest.java, cloudinary-test-common/src/main/java/com/cloudinary/test/MetadataTestHelper.java
Add support for update metadatafield set default disabled
=> Add support for update metadatafield set default disabled

cloudinary-core/src/main/java/com/cloudinary/Configuration.java, cloudinary-core/src/test/java/com/cloudinary/AuthTokenTest.java, cloudinary-core/src/test/java/com/cloudinary/analytics/AnalyticsTest.java, cloudinary-core/src/test/java/com/cloudinary/test/CloudinaryTest.java, cloudinary-core/src/test/java/com/cloudinary/transformation/LayerTest.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractUploaderTest.java
Implement major version requirements
1. secure default true
2. analytics default true
=> Implement major version requirements

java_shared.gradle
Increament Java version to Java 8.0
=> Update java version

cloudinary-core/src/main/java/com/cloudinary/Api.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java
Add derived next cursor support
=> Add derived next cursor support

cloudinary-core/src/main/java/com/cloudinary/Util.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractUploaderTest.java
Add `auto_chaptering` and `auto_transcription` to upload API
=> Add `auto_chaptering` and `auto_transcription` to upload API

cloudinary-core/src/main/java/com/cloudinary/Api.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java
Remove depreacted live from upload preset calls + tests
=> Fix upload preset tests

cloudinary-core/src/main/java/com/cloudinary/Cloudinary.java
=> Update Cloudinary constructor

cloudinary-core/src/main/java/com/cloudinary/Cloudinary.java, cloudinary-core/src/test/java/com/cloudinary/test/CloudinaryTest.java
Fix and test register upload + api strategies
=> Fix and test register upload + api strategies

cloudinary-http5/src/main/java/com/cloudinary/http5/ApiStrategy.java, cloudinary-http5/src/test/java/com/cloudinary/test/ApiTest.java
=> Fix Http client 5.0 init

cloudinary-core/src/main/java/com/cloudinary/Api.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractStructuredMetadataTest.java
Add restore by asset ids api call
=> Add restore by asset ids api call

cloudinary-core/src/main/java/com/cloudinary/Api.java, cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractFoldersApiTest.java
Add skip backup parameter to delete folder api
=> Add skip backup parameter to delete folder api

cloudinary-http5/build.gradle, cloudinary-taglib/build.gradle
Update commons package version
=> Update commons package version
